import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-spinner',
  template: `<div class="loadingio-spinner-dual-ring-e2awnc3fl38"><div class="ldio-ma4icplahk">
<div></div><div><div></div></div>
</div></div>
<style type="text/css">
@keyframes ldio-ma4icplahk {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-ma4icplahk div { box-sizing: border-box!important }
.ldio-ma4icplahk > div {
  position: absolute;
  width: 144px;
  height: 144px;
  top: 28px;
  left: 28px;
  border-radius: 50%;
  border: 16px solid #000;
  border-color: #fe718d transparent #fe718d transparent;
  animation: ldio-ma4icplahk 1s linear infinite;
}
.ldio-ma4icplahk > div:nth-child(2) { border-color: transparent }
.ldio-ma4icplahk > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-ma4icplahk > div:nth-child(2) div:before, .ldio-ma4icplahk > div:nth-child(2) div:after { 
  content: "";
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 48px;
  background: #fe718d;
  border-radius: 50%;
  box-shadow: 0 128px 0 0 #fe718d;
}
.ldio-ma4icplahk > div:nth-child(2) div:after { 
  left: -16px;
  top: 48px;
  box-shadow: 128px 0 0 0 #fe718d;
}
.loadingio-spinner-dual-ring-e2awnc3fl38 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-ma4icplahk {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-ma4icplahk div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>`,
  styleUrls: ['./spinner.component.css']
})
export class SpinnerComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
